/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRouteImport } from './routes/$owner'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OwnerIndexRouteImport } from './routes/$owner.index'
import { Route as OwnerRepoRouteImport } from './routes/$owner.$repo'
import { Route as OrganizationsOrganizationRouteImport } from './routes/organizations.$organization'
import { Route as ProfilesIdentityRouteImport } from './routes/profiles.$identity'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo.index'
import { Route as OwnerRepoActivityRouteImport } from './routes/$owner.$repo.activity'
import { Route as OwnerRepoCommitsRouteImport } from './routes/$owner.$repo.commits'
import { Route as OwnerRepoCompareRouteImport } from './routes/$owner.$repo.compare'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner.$repo.issues'
import { Route as OwnerRepoLabelsRouteImport } from './routes/$owner.$repo.labels'
import { Route as OwnerRepoMilestonesRouteImport } from './routes/$owner.$repo.milestones'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner.$repo.pulls'
import { Route as OwnerRepoSettingsRouteImport } from './routes/$owner.$repo.settings'
import { Route as OwnerRepoBlobSplatRouteImport } from './routes/$owner.$repo.blob.$'
import { Route as OwnerRepoCommitRevisionRouteImport } from './routes/$owner.$repo.commit.$revision'
import { Route as OwnerRepoIssuesIssueRouteImport } from './routes/$owner.$repo.issues.$issue'
import { Route as OwnerRepoPullsPullRouteImport } from './routes/$owner.$repo.pulls.$pull'
import { Route as OwnerRepoTreeSplatRouteImport } from './routes/$owner.$repo.tree.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/$owner',
  path: '/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => OwnerRoute,
} as any)
const OrganizationsOrganizationRoute =
  OrganizationsOrganizationRouteImport.update({
    id: '/$organization',
    path: '/$organization',
    getParentRoute: () => OrganizationsRoute,
  } as any)
const ProfilesIdentityRoute = ProfilesIdentityRouteImport.update({
  id: '/profiles/$identity',
  path: '/profiles/$identity',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoActivityRoute = OwnerRepoActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitsRoute = OwnerRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCompareRoute = OwnerRepoCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoLabelsRoute = OwnerRepoLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoMilestonesRoute = OwnerRepoMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoSettingsRoute = OwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBlobSplatRoute = OwnerRepoBlobSplatRouteImport.update({
  id: '/blob/$',
  path: '/blob/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitRevisionRoute = OwnerRepoCommitRevisionRouteImport.update({
  id: '/commit/$revision',
  path: '/commit/$revision',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesIssueRoute = OwnerRepoIssuesIssueRouteImport.update({
  id: '/$issue',
  path: '/$issue',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoPullsPullRoute = OwnerRepoPullsPullRouteImport.update({
  id: '/$pull',
  path: '/$pull',
  getParentRoute: () => OwnerRepoPullsRoute,
} as any)
const OwnerRepoTreeSplatRoute = OwnerRepoTreeSplatRouteImport.update({
  id: '/tree/$',
  path: '/tree/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/organizations/$organization': typeof OrganizationsOrganizationRoute
  '/profiles/$identity': typeof ProfilesIdentityRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/labels': typeof OwnerRepoLabelsRoute
  '/$owner/$repo/milestones': typeof OwnerRepoMilestonesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$revision': typeof OwnerRepoCommitRevisionRoute
  '/$owner/$repo/issues/$issue': typeof OwnerRepoIssuesIssueRoute
  '/$owner/$repo/pulls/$pull': typeof OwnerRepoPullsPullRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/organizations/$organization': typeof OrganizationsOrganizationRoute
  '/profiles/$identity': typeof ProfilesIdentityRoute
  '/$owner': typeof OwnerIndexRoute
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/labels': typeof OwnerRepoLabelsRoute
  '/$owner/$repo/milestones': typeof OwnerRepoMilestonesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$revision': typeof OwnerRepoCommitRevisionRoute
  '/$owner/$repo/issues/$issue': typeof OwnerRepoIssuesIssueRoute
  '/$owner/$repo/pulls/$pull': typeof OwnerRepoPullsPullRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$owner': typeof OwnerRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/organizations/$organization': typeof OrganizationsOrganizationRoute
  '/profiles/$identity': typeof ProfilesIdentityRoute
  '/$owner/': typeof OwnerIndexRoute
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/labels': typeof OwnerRepoLabelsRoute
  '/$owner/$repo/milestones': typeof OwnerRepoMilestonesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/settings': typeof OwnerRepoSettingsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$revision': typeof OwnerRepoCommitRevisionRoute
  '/$owner/$repo/issues/$issue': typeof OwnerRepoIssuesIssueRoute
  '/$owner/$repo/pulls/$pull': typeof OwnerRepoPullsPullRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$owner'
    | '/explore'
    | '/login'
    | '/notifications'
    | '/organizations'
    | '/$owner/$repo'
    | '/organizations/$organization'
    | '/profiles/$identity'
    | '/$owner/'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/labels'
    | '/$owner/$repo/milestones'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$revision'
    | '/$owner/$repo/issues/$issue'
    | '/$owner/$repo/pulls/$pull'
    | '/$owner/$repo/tree/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/notifications'
    | '/organizations'
    | '/organizations/$organization'
    | '/profiles/$identity'
    | '/$owner'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/labels'
    | '/$owner/$repo/milestones'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/settings'
    | '/$owner/$repo'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$revision'
    | '/$owner/$repo/issues/$issue'
    | '/$owner/$repo/pulls/$pull'
    | '/$owner/$repo/tree/$'
  id:
    | '__root__'
    | '/'
    | '/$owner'
    | '/explore'
    | '/login'
    | '/notifications'
    | '/organizations'
    | '/$owner/$repo'
    | '/organizations/$organization'
    | '/profiles/$identity'
    | '/$owner/'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/labels'
    | '/$owner/$repo/milestones'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$revision'
    | '/$owner/$repo/issues/$issue'
    | '/$owner/$repo/pulls/$pull'
    | '/$owner/$repo/tree/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  ProfilesIdentityRoute: typeof ProfilesIdentityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner': {
      id: '/$owner'
      path: '/$owner'
      fullPath: '/$owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/': {
      id: '/$owner/'
      path: '/'
      fullPath: '/$owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/organizations/$organization': {
      id: '/organizations/$organization'
      path: '/$organization'
      fullPath: '/organizations/$organization'
      preLoaderRoute: typeof OrganizationsOrganizationRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/profiles/$identity': {
      id: '/profiles/$identity'
      path: '/profiles/$identity'
      fullPath: '/profiles/$identity'
      preLoaderRoute: typeof ProfilesIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/activity': {
      id: '/$owner/$repo/activity'
      path: '/activity'
      fullPath: '/$owner/$repo/activity'
      preLoaderRoute: typeof OwnerRepoActivityRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commits': {
      id: '/$owner/$repo/commits'
      path: '/commits'
      fullPath: '/$owner/$repo/commits'
      preLoaderRoute: typeof OwnerRepoCommitsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/compare': {
      id: '/$owner/$repo/compare'
      path: '/compare'
      fullPath: '/$owner/$repo/compare'
      preLoaderRoute: typeof OwnerRepoCompareRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/labels': {
      id: '/$owner/$repo/labels'
      path: '/labels'
      fullPath: '/$owner/$repo/labels'
      preLoaderRoute: typeof OwnerRepoLabelsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/milestones': {
      id: '/$owner/$repo/milestones'
      path: '/milestones'
      fullPath: '/$owner/$repo/milestones'
      preLoaderRoute: typeof OwnerRepoMilestonesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/settings': {
      id: '/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof OwnerRepoSettingsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/blob/$': {
      id: '/$owner/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$owner/$repo/blob/$'
      preLoaderRoute: typeof OwnerRepoBlobSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commit/$revision': {
      id: '/$owner/$repo/commit/$revision'
      path: '/commit/$revision'
      fullPath: '/$owner/$repo/commit/$revision'
      preLoaderRoute: typeof OwnerRepoCommitRevisionRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues/$issue': {
      id: '/$owner/$repo/issues/$issue'
      path: '/$issue'
      fullPath: '/$owner/$repo/issues/$issue'
      preLoaderRoute: typeof OwnerRepoIssuesIssueRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/pulls/$pull': {
      id: '/$owner/$repo/pulls/$pull'
      path: '/$pull'
      fullPath: '/$owner/$repo/pulls/$pull'
      preLoaderRoute: typeof OwnerRepoPullsPullRouteImport
      parentRoute: typeof OwnerRepoPullsRoute
    }
    '/$owner/$repo/tree/$': {
      id: '/$owner/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$owner/$repo/tree/$'
      preLoaderRoute: typeof OwnerRepoTreeSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
  }
}

interface OwnerRepoIssuesRouteChildren {
  OwnerRepoIssuesIssueRoute: typeof OwnerRepoIssuesIssueRoute
}

const OwnerRepoIssuesRouteChildren: OwnerRepoIssuesRouteChildren = {
  OwnerRepoIssuesIssueRoute: OwnerRepoIssuesIssueRoute,
}

const OwnerRepoIssuesRouteWithChildren = OwnerRepoIssuesRoute._addFileChildren(
  OwnerRepoIssuesRouteChildren,
)

interface OwnerRepoPullsRouteChildren {
  OwnerRepoPullsPullRoute: typeof OwnerRepoPullsPullRoute
}

const OwnerRepoPullsRouteChildren: OwnerRepoPullsRouteChildren = {
  OwnerRepoPullsPullRoute: OwnerRepoPullsPullRoute,
}

const OwnerRepoPullsRouteWithChildren = OwnerRepoPullsRoute._addFileChildren(
  OwnerRepoPullsRouteChildren,
)

interface OwnerRepoRouteChildren {
  OwnerRepoActivityRoute: typeof OwnerRepoActivityRoute
  OwnerRepoCommitsRoute: typeof OwnerRepoCommitsRoute
  OwnerRepoCompareRoute: typeof OwnerRepoCompareRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRouteWithChildren
  OwnerRepoLabelsRoute: typeof OwnerRepoLabelsRoute
  OwnerRepoMilestonesRoute: typeof OwnerRepoMilestonesRoute
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRouteWithChildren
  OwnerRepoSettingsRoute: typeof OwnerRepoSettingsRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoBlobSplatRoute: typeof OwnerRepoBlobSplatRoute
  OwnerRepoCommitRevisionRoute: typeof OwnerRepoCommitRevisionRoute
  OwnerRepoTreeSplatRoute: typeof OwnerRepoTreeSplatRoute
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoActivityRoute: OwnerRepoActivityRoute,
  OwnerRepoCommitsRoute: OwnerRepoCommitsRoute,
  OwnerRepoCompareRoute: OwnerRepoCompareRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRouteWithChildren,
  OwnerRepoLabelsRoute: OwnerRepoLabelsRoute,
  OwnerRepoMilestonesRoute: OwnerRepoMilestonesRoute,
  OwnerRepoPullsRoute: OwnerRepoPullsRouteWithChildren,
  OwnerRepoSettingsRoute: OwnerRepoSettingsRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoBlobSplatRoute: OwnerRepoBlobSplatRoute,
  OwnerRepoCommitRevisionRoute: OwnerRepoCommitRevisionRoute,
  OwnerRepoTreeSplatRoute: OwnerRepoTreeSplatRoute,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

interface OwnerRouteChildren {
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface OrganizationsRouteChildren {
  OrganizationsOrganizationRoute: typeof OrganizationsOrganizationRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrganizationRoute: OrganizationsOrganizationRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  ProfilesIdentityRoute: ProfilesIdentityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
