/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerRepoRouteImport } from './routes/$owner.$repo'
import { Route as ProfilesIdentityRouteImport } from './routes/profiles.$identity'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo.index'
import { Route as OwnerRepoActivityRouteImport } from './routes/$owner.$repo.activity'
import { Route as OwnerRepoCommitsRouteImport } from './routes/$owner.$repo.commits'
import { Route as OwnerRepoCompareRouteImport } from './routes/$owner.$repo.compare'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner.$repo.issues'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner.$repo.pulls'
import { Route as OwnerRepoBlobSplatRouteImport } from './routes/$owner.$repo.blob.$'
import { Route as OwnerRepoCommitRevisionRouteImport } from './routes/$owner.$repo.commit.$revision'
import { Route as OwnerRepoIssuesIssueRouteImport } from './routes/$owner.$repo.issues.$issue'
import { Route as OwnerRepoPullsPullRouteImport } from './routes/$owner.$repo.pulls.$pull'
import { Route as OwnerRepoTreeSplatRouteImport } from './routes/$owner.$repo.tree.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdentityRoute = ProfilesIdentityRouteImport.update({
  id: '/profiles/$identity',
  path: '/profiles/$identity',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoActivityRoute = OwnerRepoActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitsRoute = OwnerRepoCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCompareRoute = OwnerRepoCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoBlobSplatRoute = OwnerRepoBlobSplatRouteImport.update({
  id: '/blob/$',
  path: '/blob/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoCommitRevisionRoute = OwnerRepoCommitRevisionRouteImport.update({
  id: '/commit/$revision',
  path: '/commit/$revision',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesIssueRoute = OwnerRepoIssuesIssueRouteImport.update({
  id: '/$issue',
  path: '/$issue',
  getParentRoute: () => OwnerRepoIssuesRoute,
} as any)
const OwnerRepoPullsPullRoute = OwnerRepoPullsPullRouteImport.update({
  id: '/$pull',
  path: '/$pull',
  getParentRoute: () => OwnerRepoPullsRoute,
} as any)
const OwnerRepoTreeSplatRoute = OwnerRepoTreeSplatRouteImport.update({
  id: '/tree/$',
  path: '/tree/$',
  getParentRoute: () => OwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/profiles/$identity': typeof ProfilesIdentityRoute
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$revision': typeof OwnerRepoCommitRevisionRoute
  '/$owner/$repo/issues/$issue': typeof OwnerRepoIssuesIssueRoute
  '/$owner/$repo/pulls/$pull': typeof OwnerRepoPullsPullRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/profiles/$identity': typeof ProfilesIdentityRoute
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$revision': typeof OwnerRepoCommitRevisionRoute
  '/$owner/$repo/issues/$issue': typeof OwnerRepoIssuesIssueRoute
  '/$owner/$repo/pulls/$pull': typeof OwnerRepoPullsPullRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/profiles/$identity': typeof ProfilesIdentityRoute
  '/$owner/$repo/activity': typeof OwnerRepoActivityRoute
  '/$owner/$repo/commits': typeof OwnerRepoCommitsRoute
  '/$owner/$repo/compare': typeof OwnerRepoCompareRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRouteWithChildren
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof OwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$revision': typeof OwnerRepoCommitRevisionRoute
  '/$owner/$repo/issues/$issue': typeof OwnerRepoIssuesIssueRoute
  '/$owner/$repo/pulls/$pull': typeof OwnerRepoPullsPullRoute
  '/$owner/$repo/tree/$': typeof OwnerRepoTreeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/$owner/$repo'
    | '/profiles/$identity'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$revision'
    | '/$owner/$repo/issues/$issue'
    | '/$owner/$repo/pulls/$pull'
    | '/$owner/$repo/tree/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/profiles/$identity'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$revision'
    | '/$owner/$repo/issues/$issue'
    | '/$owner/$repo/pulls/$pull'
    | '/$owner/$repo/tree/$'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/login'
    | '/$owner/$repo'
    | '/profiles/$identity'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/compare'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$revision'
    | '/$owner/$repo/issues/$issue'
    | '/$owner/$repo/pulls/$pull'
    | '/$owner/$repo/tree/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
  ProfilesIdentityRoute: typeof ProfilesIdentityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$identity': {
      id: '/profiles/$identity'
      path: '/profiles/$identity'
      fullPath: '/profiles/$identity'
      preLoaderRoute: typeof ProfilesIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/activity': {
      id: '/$owner/$repo/activity'
      path: '/activity'
      fullPath: '/$owner/$repo/activity'
      preLoaderRoute: typeof OwnerRepoActivityRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commits': {
      id: '/$owner/$repo/commits'
      path: '/commits'
      fullPath: '/$owner/$repo/commits'
      preLoaderRoute: typeof OwnerRepoCommitsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/compare': {
      id: '/$owner/$repo/compare'
      path: '/compare'
      fullPath: '/$owner/$repo/compare'
      preLoaderRoute: typeof OwnerRepoCompareRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/blob/$': {
      id: '/$owner/$repo/blob/$'
      path: '/blob/$'
      fullPath: '/$owner/$repo/blob/$'
      preLoaderRoute: typeof OwnerRepoBlobSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/commit/$revision': {
      id: '/$owner/$repo/commit/$revision'
      path: '/commit/$revision'
      fullPath: '/$owner/$repo/commit/$revision'
      preLoaderRoute: typeof OwnerRepoCommitRevisionRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues/$issue': {
      id: '/$owner/$repo/issues/$issue'
      path: '/$issue'
      fullPath: '/$owner/$repo/issues/$issue'
      preLoaderRoute: typeof OwnerRepoIssuesIssueRouteImport
      parentRoute: typeof OwnerRepoIssuesRoute
    }
    '/$owner/$repo/pulls/$pull': {
      id: '/$owner/$repo/pulls/$pull'
      path: '/$pull'
      fullPath: '/$owner/$repo/pulls/$pull'
      preLoaderRoute: typeof OwnerRepoPullsPullRouteImport
      parentRoute: typeof OwnerRepoPullsRoute
    }
    '/$owner/$repo/tree/$': {
      id: '/$owner/$repo/tree/$'
      path: '/tree/$'
      fullPath: '/$owner/$repo/tree/$'
      preLoaderRoute: typeof OwnerRepoTreeSplatRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
  }
}

interface OwnerRepoIssuesRouteChildren {
  OwnerRepoIssuesIssueRoute: typeof OwnerRepoIssuesIssueRoute
}

const OwnerRepoIssuesRouteChildren: OwnerRepoIssuesRouteChildren = {
  OwnerRepoIssuesIssueRoute: OwnerRepoIssuesIssueRoute,
}

const OwnerRepoIssuesRouteWithChildren = OwnerRepoIssuesRoute._addFileChildren(
  OwnerRepoIssuesRouteChildren,
)

interface OwnerRepoPullsRouteChildren {
  OwnerRepoPullsPullRoute: typeof OwnerRepoPullsPullRoute
}

const OwnerRepoPullsRouteChildren: OwnerRepoPullsRouteChildren = {
  OwnerRepoPullsPullRoute: OwnerRepoPullsPullRoute,
}

const OwnerRepoPullsRouteWithChildren = OwnerRepoPullsRoute._addFileChildren(
  OwnerRepoPullsRouteChildren,
)

interface OwnerRepoRouteChildren {
  OwnerRepoActivityRoute: typeof OwnerRepoActivityRoute
  OwnerRepoCommitsRoute: typeof OwnerRepoCommitsRoute
  OwnerRepoCompareRoute: typeof OwnerRepoCompareRoute
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRouteWithChildren
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRouteWithChildren
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoBlobSplatRoute: typeof OwnerRepoBlobSplatRoute
  OwnerRepoCommitRevisionRoute: typeof OwnerRepoCommitRevisionRoute
  OwnerRepoTreeSplatRoute: typeof OwnerRepoTreeSplatRoute
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoActivityRoute: OwnerRepoActivityRoute,
  OwnerRepoCommitsRoute: OwnerRepoCommitsRoute,
  OwnerRepoCompareRoute: OwnerRepoCompareRoute,
  OwnerRepoIssuesRoute: OwnerRepoIssuesRouteWithChildren,
  OwnerRepoPullsRoute: OwnerRepoPullsRouteWithChildren,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoBlobSplatRoute: OwnerRepoBlobSplatRoute,
  OwnerRepoCommitRevisionRoute: OwnerRepoCommitRevisionRoute,
  OwnerRepoTreeSplatRoute: OwnerRepoTreeSplatRoute,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
  ProfilesIdentityRoute: ProfilesIdentityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
